/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class TConverterString extends Token
{
    public TConverterString()
    {
        super.setText("\"");
    }

    public TConverterString(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TConverterString(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTConverterString(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TConverterString text.");
    }
}
