/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class TQuebraLinha extends Token
{
    public TQuebraLinha()
    {
        super.setText("\\n");
    }

    public TQuebraLinha(int line, int pos)
    {
        super.setText("\\n");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQuebraLinha(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQuebraLinha(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQuebraLinha text.");
    }
}
