/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.node;

import calculadora.analysis.*;

@SuppressWarnings("nls")
public final class TRetorna extends Token
{
    public TRetorna()
    {
        super.setText("retorne");
    }

    public TRetorna(int line, int pos)
    {
        super.setText("retorne");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRetorna(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRetorna(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRetorna text.");
    }
}
