/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.analysis;

import calculadora.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTTipoNumero(TTipoNumero node);
    void caseTTipoBooleano(TTipoBooleano node);
    void caseTTipoCaractere(TTipoCaractere node);
    void caseTTipoVetor(TTipoVetor node);
    void caseTComandoSe(TComandoSe node);
    void caseTComandoSenao(TComandoSenao node);
    void caseTComandoPara(TComandoPara node);
    void caseTComandoParaCada(TComandoParaCada node);
    void caseTComandoEnquanto(TComandoEnquanto node);
    void caseTRetorna(TRetorna node);
    void caseTExibir(TExibir node);
    void caseTLer(TLer node);
    void caseTBooleano(TBooleano node);
    void caseTComecoBloco(TComecoBloco node);
    void caseTFinalBloco(TFinalBloco node);
    void caseTId(TId node);
    void caseTPalavra(TPalavra node);
    void caseTNumero(TNumero node);
    void caseTPontoFinal(TPontoFinal node);
    void caseTVirgula(TVirgula node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTMaiorQue(TMaiorQue node);
    void caseTMenorQue(TMenorQue node);
    void caseTMaiorIgualQue(TMaiorIgualQue node);
    void caseTMenorIgualQue(TMenorIgualQue node);
    void caseTAtrib(TAtrib node);
    void caseTIgual(TIgual node);
    void caseTNegacao(TNegacao node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTBarraReta(TBarraReta node);
    void caseTTab(TTab node);
    void caseTColchEsq(TColchEsq node);
    void caseTColchDir(TColchDir node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTVazio(TVazio node);
    void caseTQuebraLinha(TQuebraLinha node);
    void caseTCaractere(TCaractere node);
    void caseTString(TString node);
    void caseTComentarioLinha(TComentarioLinha node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
