/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.analysis;

import calculadora.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTTipoBase(TTipoBase node);
    void caseTComando(TComando node);
    void caseTComecoBloco(TComecoBloco node);
    void caseTFinalBloco(TFinalBloco node);
    void caseTId(TId node);
    void caseTPalavra(TPalavra node);
    void caseTInteiro(TInteiro node);
    void caseTPontoFinal(TPontoFinal node);
    void caseTVirgula(TVirgula node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTMaiorQue(TMaiorQue node);
    void caseTMenorQue(TMenorQue node);
    void caseTMaiorIgualQue(TMaiorIgualQue node);
    void caseTMenorIgualQue(TMenorIgualQue node);
    void caseTAtrib(TAtrib node);
    void caseTIgual(TIgual node);
    void caseTNegacao(TNegacao node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTBarraReta(TBarraReta node);
    void caseTAspasSimples(TAspasSimples node);
    void caseTQuebraLinha(TQuebraLinha node);
    void caseTConverterString(TConverterString node);
    void caseTColchEsq(TColchEsq node);
    void caseTColchDir(TColchDir node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
